# Generated by Django 4.0 on 2021-12-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=50, unique=True, verbose_name='Телеграмм аккаунт')),
                ('cookies', models.CharField(max_length=255, verbose_name='Печеньки')),
                ('marks', models.CharField(blank=True, max_length=500, verbose_name='Оценки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
