# Generated by Django 4.0 on 2021-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cookies',
            field=models.CharField(blank=True, max_length=255, verbose_name='Печеньки'),
        ),
    ]
