# Generated by Django 4.0 on 2021-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_profile_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cookies',
            field=models.FileField(upload_to='cookies/', verbose_name='Печеньки'),
        ),
    ]
