# Generated by Django 4.0 on 2022-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_profile_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cookies',
            field=models.BinaryField(verbose_name='Печеньки'),
        ),
    ]
